//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.15 at 06:39:55 PM CEST 
//


package project.xml.AgentMegaTravel.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the project.xml.AgentMegaTravel.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NewElement_QNAME = new QName("http://www.mega-travel.com/soap", "newElement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: project.xml.AgentMegaTravel.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAdditionalServiseResponse }
     * 
     */
    public GetAdditionalServiseResponse createGetAdditionalServiseResponse() {
        return new GetAdditionalServiseResponse();
    }

    /**
     * Create an instance of {@link GetAddressResponse }
     * 
     */
    public GetAddressResponse createGetAddressResponse() {
        return new GetAddressResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationUtitResponse }
     * 
     */
    public GetAccommodationUtitResponse createGetAccommodationUtitResponse() {
        return new GetAccommodationUtitResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitRequest }
     * 
     */
    public GetAccommodationUnitRequest createGetAccommodationUnitRequest() {
        return new GetAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationResponse }
     * 
     */
    public GetAccommodationResponse createGetAccommodationResponse() {
        return new GetAccommodationResponse();
    }

    /**
     * Create an instance of {@link PostAccommodationResponse }
     * 
     */
    public PostAccommodationResponse createPostAccommodationResponse() {
        return new PostAccommodationResponse();
    }

    /**
     * Create an instance of {@link GetAllAdditionalServiceResponse }
     * 
     */
    public GetAllAdditionalServiceResponse createGetAllAdditionalServiceResponse() {
        return new GetAllAdditionalServiceResponse();
    }

    /**
     * Create an instance of {@link GetPricingResponse }
     * 
     */
    public GetPricingResponse createGetPricingResponse() {
        return new GetPricingResponse();
    }

    /**
     * Create an instance of {@link GetAdditionalServiseResponse.AdditionalServices }
     * 
     */
    public GetAdditionalServiseResponse.AdditionalServices createGetAdditionalServiseResponseAdditionalServices() {
        return new GetAdditionalServiseResponse.AdditionalServices();
    }

    /**
     * Create an instance of {@link GetAddressResponse.Address }
     * 
     */
    public GetAddressResponse.Address createGetAddressResponseAddress() {
        return new GetAddressResponse.Address();
    }

    /**
     * Create an instance of {@link GetReservationResponse }
     * 
     */
    public GetReservationResponse createGetReservationResponse() {
        return new GetReservationResponse();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link project.xml.AgentMegaTravel.model.Address }
     * 
     */
    public project.xml.AgentMegaTravel.model.Address createAddress() {
        return new project.xml.AgentMegaTravel.model.Address();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Privilege }
     * 
     */
    public Privilege createPrivilege() {
        return new Privilege();
    }

    /**
     * Create an instance of {@link project.xml.AgentMegaTravel.model.Accommodation }
     * 
     */
    public project.xml.AgentMegaTravel.model.Accommodation createAccommodation() {
        return new project.xml.AgentMegaTravel.model.Accommodation();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link project.xml.AgentMegaTravel.model.AdditionalServices }
     * 
     */
    public project.xml.AgentMegaTravel.model.AdditionalServices createAdditionalServices() {
        return new project.xml.AgentMegaTravel.model.AdditionalServices();
    }

    /**
     * Create an instance of {@link project.xml.AgentMegaTravel.model.AccommodationUnit }
     * 
     */
    public project.xml.AgentMegaTravel.model.AccommodationUnit createAccommodationUnit() {
        return new project.xml.AgentMegaTravel.model.AccommodationUnit();
    }

    /**
     * Create an instance of {@link project.xml.AgentMegaTravel.model.Pricing }
     * 
     */
    public project.xml.AgentMegaTravel.model.Pricing createPricing() {
        return new project.xml.AgentMegaTravel.model.Pricing();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link GetReservationRequest }
     * 
     */
    public GetReservationRequest createGetReservationRequest() {
        return new GetReservationRequest();
    }

    /**
     * Create an instance of {@link GetAddressRequest }
     * 
     */
    public GetAddressRequest createGetAddressRequest() {
        return new GetAddressRequest();
    }

    /**
     * Create an instance of {@link GetAdditionalServiceRequest }
     * 
     */
    public GetAdditionalServiceRequest createGetAdditionalServiceRequest() {
        return new GetAdditionalServiceRequest();
    }

    /**
     * Create an instance of {@link GetPricingRequest }
     * 
     */
    public GetPricingRequest createGetPricingRequest() {
        return new GetPricingRequest();
    }

    /**
     * Create an instance of {@link PostAccommodationRequest }
     * 
     */
    public PostAccommodationRequest createPostAccommodationRequest() {
        return new PostAccommodationRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationUtitResponse.AccommodationUnit }
     * 
     */
    public GetAccommodationUtitResponse.AccommodationUnit createGetAccommodationUtitResponseAccommodationUnit() {
        return new GetAccommodationUtitResponse.AccommodationUnit();
    }

    /**
     * Create an instance of {@link GetAccommodationRequest }
     * 
     */
    public GetAccommodationRequest createGetAccommodationRequest() {
        return new GetAccommodationRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitRequest.AccommodationUnit }
     * 
     */
    public GetAccommodationUnitRequest.AccommodationUnit createGetAccommodationUnitRequestAccommodationUnit() {
        return new GetAccommodationUnitRequest.AccommodationUnit();
    }

    /**
     * Create an instance of {@link GetAccommodationResponse.Accommodation }
     * 
     */
    public GetAccommodationResponse.Accommodation createGetAccommodationResponseAccommodation() {
        return new GetAccommodationResponse.Accommodation();
    }

    /**
     * Create an instance of {@link PostAccommodationResponse.Accommodation }
     * 
     */
    public PostAccommodationResponse.Accommodation createPostAccommodationResponseAccommodation() {
        return new PostAccommodationResponse.Accommodation();
    }

    /**
     * Create an instance of {@link GetAllAdditionalServiceResponse.AdditionalServices }
     * 
     */
    public GetAllAdditionalServiceResponse.AdditionalServices createGetAllAdditionalServiceResponseAdditionalServices() {
        return new GetAllAdditionalServiceResponse.AdditionalServices();
    }

    /**
     * Create an instance of {@link GetPricingResponse.Pricing }
     * 
     */
    public GetPricingResponse.Pricing createGetPricingResponsePricing() {
        return new GetPricingResponse.Pricing();
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mega-travel.com/soap", name = "newElement")
    public JAXBElement<Object> createNewElement(Object value) {
        return new JAXBElement<Object>(_NewElement_QNAME, Object.class, null, value);
    }

}
