server:
  port: ${PORT:8762}
  ssl:
    enabled: true
    key-store: classpath:admin.jks
    key-store-password: password
    key-alias: admin
web:
  service:
    username: tanjica
    password: password
security:
  require-ssl: true
  
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/ 
spring:
  application:
    name: AdminService
  datasource:
    url: jdbc:mysql://localhost:3306/megatravel?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: sara0301997188128
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true