spring:
  application:
    name: zuul-server
server:  
  port: ${PORT:8081}
  ssl:
    enabled: true
    key-store: classpath:zuul.jks
    key-store-password: password
    key-alias: zuul


security:
  require-ssl: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/ 

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    gateway:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

zuul:
  routes:
    AdminService:
      sensitive-headers: Authorization
      serviceId: AdminService
    AgentMegaTravel:
      sensitive-headers: Authorization
      serviceId: AgentMegaTravel
    MegaTravel:
      sensitive-headers: Authorization
      serviceId: MegaTravel
    ReservationService:
      sensitive-headers: Authorization
      serviceId: ReservationService
  sensitive-headers: Authorization
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    socket-timeout-millis: 30000
  sslHostnameValidationEnabled: false
  ribbon:
    IsSecured: true
    ConnectTimeout:  10000
    ReadTimeout:  10000
    eureka:
      enabled: true
    TrustStore: classpath:zuul.jks
    TrustStorePassword : password
    IsHostnameValidationRequired: false