//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 08:36:35 PM CEST 
//


package project.xml.AgentMegaTravel.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the project.xml.AgentMegaTravel.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: project.xml.AgentMegaTravel.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SaveMessageResponse }
     * 
     */
    public SaveMessageResponse createSaveMessageResponse() {
        return new SaveMessageResponse();
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Privilege }
     * 
     */
    public Privilege createPrivilege() {
        return new Privilege();
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link AccommodationUnit }
     * 
     */
    public AccommodationUnit createAccommodationUnit() {
        return new AccommodationUnit();
    }

    /**
     * Create an instance of {@link Pricing }
     * 
     */
    public Pricing createPricing() {
        return new Pricing();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link AdditionalServices }
     * 
     */
    public AdditionalServices createAdditionalServices() {
        return new AdditionalServices();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link GetPriceResponse }
     * 
     */
    public GetPriceResponse createGetPriceResponse() {
        return new GetPriceResponse();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link SaveReservationRequest }
     * 
     */
    public SaveReservationRequest createSaveReservationRequest() {
        return new SaveReservationRequest();
    }

    /**
     * Create an instance of {@link SaveAccommodationUnitRequest }
     * 
     */
    public SaveAccommodationUnitRequest createSaveAccommodationUnitRequest() {
        return new SaveAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link SaveMessageRequest }
     * 
     */
    public SaveMessageRequest createSaveMessageRequest() {
        return new SaveMessageRequest();
    }

    /**
     * Create an instance of {@link GetAdditionalServiceResponse }
     * 
     */
    public GetAdditionalServiceResponse createGetAdditionalServiceResponse() {
        return new GetAdditionalServiceResponse();
    }

    /**
     * Create an instance of {@link GetAgentRequest }
     * 
     */
    public GetAgentRequest createGetAgentRequest() {
        return new GetAgentRequest();
    }

    /**
     * Create an instance of {@link GetAdditionalServiceRequest }
     * 
     */
    public GetAdditionalServiceRequest createGetAdditionalServiceRequest() {
        return new GetAdditionalServiceRequest();
    }

    /**
     * Create an instance of {@link GetMessagesRequest }
     * 
     */
    public GetMessagesRequest createGetMessagesRequest() {
        return new GetMessagesRequest();
    }

    /**
     * Create an instance of {@link GetMessageResponse }
     * 
     */
    public GetMessageResponse createGetMessageResponse() {
        return new GetMessageResponse();
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link GetPriceRequest }
     * 
     */
    public GetPriceRequest createGetPriceRequest() {
        return new GetPriceRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationRequest }
     * 
     */
    public GetAccommodationRequest createGetAccommodationRequest() {
        return new GetAccommodationRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitRequest }
     * 
     */
    public GetAccommodationUnitRequest createGetAccommodationUnitRequest() {
        return new GetAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link SaveAccommodationUnitResponse }
     * 
     */
    public SaveAccommodationUnitResponse createSaveAccommodationUnitResponse() {
        return new SaveAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitResponse }
     * 
     */
    public GetAccommodationUnitResponse createGetAccommodationUnitResponse() {
        return new GetAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link GetAgentReposnse }
     * 
     */
    public GetAgentReposnse createGetAgentReposnse() {
        return new GetAgentReposnse();
    }

    /**
     * Create an instance of {@link SaveReservationResponse }
     * 
     */
    public SaveReservationResponse createSaveReservationResponse() {
        return new SaveReservationResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationResponse }
     * 
     */
    public GetAccommodationResponse createGetAccommodationResponse() {
        return new GetAccommodationResponse();
    }

    /**
     * Create an instance of {@link AccommodationUnitRequest }
     * 
     */
    public AccommodationUnitRequest createAccommodationUnitRequest() {
        return new AccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link AccommodationUnitResponse }
     * 
     */
    public AccommodationUnitResponse createAccommodationUnitResponse() {
        return new AccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link AccommodationResponse }
     * 
     */
    public AccommodationResponse createAccommodationResponse() {
        return new AccommodationResponse();
    }

    /**
     * Create an instance of {@link AccommodationRequest }
     * 
     */
    public AccommodationRequest createAccommodationRequest() {
        return new AccommodationRequest();
    }

    /**
     * Create an instance of {@link ReservationResponse }
     * 
     */
    public ReservationResponse createReservationResponse() {
        return new ReservationResponse();
    }

    /**
     * Create an instance of {@link ReservationRequest }
     * 
     */
    public ReservationRequest createReservationRequest() {
        return new ReservationRequest();
    }

    /**
     * Create an instance of {@link MessageRequest }
     * 
     */
    public MessageRequest createMessageRequest() {
        return new MessageRequest();
    }

    /**
     * Create an instance of {@link MessageResponse }
     * 
     */
    public MessageResponse createMessageResponse() {
        return new MessageResponse();
    }

}
