//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.15 at 06:39:55 PM CEST 
//


package project.besp.MegaTravel.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the project.xml.AgentMegaTravel.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

   // private final static QName _NewElement_QNAME = new QName("http://www.mega-travel.com/soap", "newElement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: project.xml.AgentMegaTravel.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAdditionalServiceResponse }
     * 
     */
    public GetAdditionalServiceResponse createGetAdditionalServiseResponse() {
        return new GetAdditionalServiceResponse();
    }

    public GetAllAccommodationUnitsRequest createGetAllAccommodationUnitsRequest() {
    	return new GetAllAccommodationUnitsRequest();
    	
    }
    public GetAllAccommodationUnitsResponse createGetAllAccommodationUnitsResponse() {
    	return new GetAllAccommodationUnitsResponse();
    	
    }
    /**
     * Create an instance of {@link GetAddressResponse }
     * 
     */
    public GetAddressResponse createGetAddressResponse() {
        return new GetAddressResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitResponse }
     * 
     */
    public GetAccommodationUnitResponse createGetAccommodationUtitResponse() {
        return new GetAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitRequest }
     * 
     */
    public GetAccommodationUnitRequest createGetAccommodationUnitRequest() {
        return new GetAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationResponse }
     * 
     */
    public GetAccommodationResponse createGetAccommodationResponse() {
        return new GetAccommodationResponse();
    }

    /**
     * Create an instance of {@link PostAccommodationResponse }
     * 
     */
    public PostAccommodationResponse createPostAccommodationResponse() {
        return new PostAccommodationResponse();
    }

    /**
     * Create an instance of {@link GetAllAdditionalServiceResponse }
     * 
     */
    public GetAllAdditionalServiceResponse createGetAllAdditionalServiceResponse() {
        return new GetAllAdditionalServiceResponse();
    }

    /**
     * Create an instance of {@link GetPricingResponse }
     * 
     */
    public GetPricingResponse createGetPricingResponse() {
        return new GetPricingResponse();
    }

    /**
     * Create an instance of {@link GetAdditionalServiceResponse.AdditionalServices }
     * 
     */
 

    /**
     * Create an instance of {@link GetAddressResponse.Address }
     * 
     */


    /**
     * Create an instance of {@link GetReservationResponse }
     * 
     */
    public GetReservationResponse createGetReservationResponse() {
        return new GetReservationResponse();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link User }
     * 
     */


    /**
     * Create an instance of {@link project.xml.AgentMegaTravel.model.Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */


  
    /**
     * Create an instance of {@link project.xml.AgentMegaTravel.model.Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link project.xml.AgentMegaTravel.model.AdditionalServices }
     * 
     */
    public AdditionalServices createAdditionalServices() {
        return new AdditionalServices();
    }

    /**
     * Create an instance of {@link project.xml.AgentMegaTravel.model.AccommodationUnit }
     * 
     */
    public AccommodationUnit createAccommodationUnit() {
        return new AccommodationUnit();
    }

    /**
     * Create an instance of {@link project.xml.AgentMegaTravel.model.Pricing }
     * 
     */
    public Pricing createPricing() {
        return new Pricing();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link GetReservationRequest }
     * 
     */
    public GetReservationRequest createGetReservationRequest() {
        return new GetReservationRequest();
    }

    /**
     * Create an instance of {@link GetAddressRequest }
     * 
     */
    public GetAddressRequest createGetAddressRequest() {
        return new GetAddressRequest();
    }

    /**
     * Create an instance of {@link GetAdditionalServiceRequest }
     * 
     */
    public GetAdditionalServiceRequest createGetAdditionalServiceRequest() {
        return new GetAdditionalServiceRequest();
    }

    /**
     * Create an instance of {@link GetPricingRequest }
     * 
     */
    public GetPricingRequest createGetPricingRequest() {
        return new GetPricingRequest();
    }

    /**
     * Create an instance of {@link PostAccommodationRequest }
     * 
     */
    public PostAccommodationRequest createPostAccommodationRequest() {
        return new PostAccommodationRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitResponse.AccommodationUnit }
     * 
     */

    /**
     * Create an instance of {@link GetAccommodationRequest }
     * 
     */
    public GetAccommodationRequest createGetAccommodationRequest() {
        return new GetAccommodationRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitRequest.AccommodationUnit }
     * 
     */


    /**
     * Create an instance of {@link PostAccommodationResponse.Accommodation }
     * 
     */
 
    /**
     * Create an instance of {@link GetAllAdditionalServiceResponse.AdditionalServices }
     * 
     */


    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */


}
